---
- hosts: 192.168.10.51
  tasks:
    - name: Copy File to Host
      ansible.builtin.copy:
        src: ~/Downloads/oo.deb
        dest: ~/Downloads/oo.deb
        owner: jhunt
        group: jhunt
        mode: '0774'